package shing;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.SQLException;
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        juname = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jpass = new javax.swing.JPasswordField();
        jckbox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRATION FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(145, 22, 196, 21);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(36, 71, 50, 18);

        jname.setBackground(new java.awt.Color(0, 0, 0));
        jname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jname);
        jname.setBounds(171, 70, 297, 27);

        juname.setBackground(new java.awt.Color(0, 0, 0));
        juname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        juname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(juname);
        juname.setBounds(171, 109, 297, 30);

        jphone.setBackground(new java.awt.Color(0, 0, 0));
        jphone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jphone.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jphone);
        jphone.setBounds(171, 147, 297, 30);

        jemail.setBackground(new java.awt.Color(0, 0, 0));
        jemail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jemail.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jemail);
        jemail.setBounds(171, 190, 297, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(35, 306, 209, 39);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("I Have An Account. Login.");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 370, 150, 16);

        jpass.setBackground(new java.awt.Color(0, 0, 0));
        jpass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jpass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jpass);
        jpass.setBounds(171, 233, 297, 30);

        jckbox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jckbox.setForeground(new java.awt.Color(0, 0, 0));
        jckbox.setText("View Password");
        jckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckboxActionPerformed(evt);
            }
        });
        jPanel1.add(jckbox);
        jckbox.setBounds(365, 281, 110, 19);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("USERNAME");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(36, 109, 90, 18);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("PHONE");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(36, 152, 70, 18);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("EMAIL");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(36, 196, 51, 18);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("PASSWORD");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(36, 239, 100, 18);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(262, 306, 209, 39);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eric David\\OneDrive\\Documents\\menu\\466955411_1670820317109145_1811587893855129997_n.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = jname.getText();
        String uname = juname.getText();
        String phone = jphone.getText();
        String email = jemail.getText();
        String pass = jpass.getText();

        try{
            Statement s = (Statement) db.mycon().createStatement();
            s.executeUpdate("INSERT INTO users (Name, User_Name, Email, Password, phone) " +
                "VALUES ('" + name + "', '" + uname + "', '" + email + "', '" + pass + "', '" + phone + "')");

            JOptionPane.showMessageDialog(rootPane, "YOU HAVE SUCCEFULLY CREATED AN ACCOUNT. GO BACK TO LOGIN");
            this.setVisible(false);
            new loginF().setVisible(true);
        }catch (HeadlessException | SQLException e){

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new loginF().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckboxActionPerformed
        if(jckbox.isSelected()){
            jpass.setEchoChar((char)0);
        }
        else{
            jpass.setEchoChar('*');
        }
    }//GEN-LAST:event_jckboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jname.setText("");
        juname.setText("");
        jphone.setText("");
        jemail.setText("");
        jpass.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jckbox;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jname;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField juname;
    // End of variables declaration//GEN-END:variables
}
